### ISSUE TITLE
Getting error using BlinkTradeJS in new node application

### ISSUE THREAD

**Issue by ElissandroMendes** [blinktrade/BlinkTradeJS#41]
Hi Guys,

I'm testing the API.

In a new node application: 
```javascript
npm init
npm install blinktrade
```
Then when running this code:
```javascript
var BlinkTradeWS = require('blinktrade').BlinkTradeWS;

var blinktrade = new BlinkTradeWS();

blinktrade.connect().then(function() {
  return blinktrade.login({ username: 'rodrigo', password: 'abc12345' });
}).then(function(logged) {
  console.log(logged);
}).catch(function(err) {
  console.log(err);
});
```
Get this error:
```javascript
throw new Error('Error: ' + data.Detail + ' ' + data.Description);
        ^
Error: Error: Missing tag BrokerID Invalid message
at WebSocketTransport.onMessage (.../blockchain/blinktrade_examples/node_modules/blinktrade/lib/transpo
rts/websocket.js:156:15)
    at WebSocket.onMessage (.../blinktrade_examples/node_modules/ws/lib/EventTarget.js:99:16)
    at WebSocket.emit (events.js:160:13)
```

If I try execute any code in node_modules/examples folder, run correctly!

Could you have any advices about this ?

Thanks

**Comment by cesardeazevedo** [comment]
Hi, which blinktrade version got installed? if installed `0.1.0-beta.4` i've probably did a mistake when publish our new version on npm 😄, you should still use the last stable version `0.0.21`, and also, in future versions brokerId on the constructor will be required, i will also update the examples.

```js
const blinktrade = new BlinkTradeWS({
  brokerId: 4, // uses foxbit
  prod: false, // uses testnet
});
```

 Let me know if you got it.

**Comment by ElissandroMendes** [comment]
It worked, thanks @cesardeazevedo
