### ISSUE TITLE
Balance call fails 

### ISSUE THREAD

**Issue by machard** [blinktrade/BlinkTradeJS#49]
Hi,

Since today, when i call balance it fails with

```
{ FetchError: invalid json response body at https://api.blinktrade.com/tapi/v1/message reason: Unexpected token < in JSON at position 0
    at /Users/matthieuachard/Documents/bitcoin/arnaud-bitcoin-trader/node_modules/node-fetch/lib/body.js:48:31
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  name: 'FetchError',
  message: 'invalid json response body at https://api.blinktrade.com/tapi/v1/message reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }
```

Any idea ?

**Comment by machard** [comment]
Looks like its been fixed on your side!
