### ISSUE TITLE
Minor: `.sendOrder` only accepts Integer amounts

### ISSUE THREAD

**Issue by amingilani** [blinktrade/BlinkTradeJS#7]
This is a minor annoyance and nothing more. Please feel free to close this and any of my requests that you don't agree with under a `won't fix` label :)

Typing this:
```javascript
blinktrade.sendOrder({
    "side": "2", // Sell
    "price": parseInt(1 * 1e8), // 1 PKR
    "amount": "519153",
    "symbol": "BTCPKR",
})
```

Will result in the following error:
```
Error: Error: Invalid value tag(OrderQty)=519153 Invalid message
    at BlinkTradeWS.onMessage (/Users/gilani/Sandbox/payload-urdubit/node_modules/blinktrade/lib/wsTransport.js:165:15)
    at WebSocket.onMessage (/Users/gilani/Sandbox/payload-urdubit/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/gilani/Sandbox/payload-urdubit/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/gilani/Sandbox/payload-urdubit/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/Users/gilani/Sandbox/payload-urdubit/node_modules/ws/lib/Receiver.js:371:5)
    at /Users/gilani/Sandbox/payload-urdubit/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/Users/gilani/Sandbox/payload-urdubit/node_modules/ws/lib/Receiver.js:347:3)
```

Because the API expects a strict integer. However, typing the following will work:
```javascript
blinktrade.sendOrder({
    "side": "2", // Sell
    "price": parseInt(1 * 1e8), // 1 PKR
    "amount": parseInt("519153"),
    "symbol": "BTCPKR",
})

**Comment by cesardeazevedo** [comment]
Yes, i agree, but i think we won't fix that, because we want to force and make sure to you are passing and formatting the right amount and price...

I'm plan to implement a better data validation to avoid these issues, but i'll close this for now.
